---

- name: Send a Slack Notification
  hosts: localhost
  vars_files:
    - user_token.yml
    - msg.yml
  tasks:
  - name: Send a simple message
    community.general.slack:
      channel : '#automation'
      token: '{{ user }}' 
      msg: 'Message before editing' 
    register: output
  - debug: msg="{{ output }}"
  - name: Add related information
    community.general.slack:
      channel: '{{ output.channel }}'
      token: '{{ user }}'
      message_id: '{{ output.ts }}'
      color: good
      msg: 'Message after being edited'
